stages:
  download:
    cmd: python src/data/download_dataset.py
    deps:
      - src/data/download_dataset.py
    outs:
      - data/raw/mit-bih-arrhythmia-database-1.0.0

  preprocess:
    cmd: python -m src.data.generate_data --mode deterministic
    deps:
      - data/raw/mit-bih-arrhythmia-database-1.0.0
      - src/data/generate_data.py
      - src/data/features.py
      - src/data/splitter.py
      - src/utils.py
    outs:
      - data/interim/mitbih_combined_records.csv
      - data/interim/mitbih_features.csv
      - data/interim/mitbih_features_only.csv
      - data/processed/base
      - data/processed/feat

  generate_sequences:
    cmd: python -m src.data.generate_sequences
    deps:
      - data/interim/mitbih_features_only.csv
      - src/data/generate_sequences.py
      - src/data/splitter.py
      - src/config.py
      - config.yaml
    outs:
      - data/processed/seq
      - src/saved_models/scaler_seq.joblib

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - data/processed/feat/mitbih_test_features.csv
      - src/saved_models/modelCNNMLP.keras
      - src/saved_models/modelSeq2Seq.keras
      - src/saved_models/modelTransformer.keras
      - src/evaluate.py
